install:
    - gem install bundler
    - bundle --version
    - bundle install
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - jruby-19mode
  - jruby-9.0.1.0

jobs:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-9.0.1.0
